### ISSUE TITLE
关于前置func和后置func

### ISSUE THREAD

**Issue by mrzhangs520** [sunquakes/jsonrpc4go#1]
![image](https://user-images.githubusercontent.com/48706034/115494033-6731a400-a297-11eb-9b1e-89bc6060d33d.png)
你好，项目作者。希望这里能增加两个func，用来预处理rpc请求前置和后置。例如：
注册一个前置func，用来鉴定请求权限。
注册一个后置func，用来记录rpc日志。
等等。。。

**Comment by sunquakes** [comment]
你好：
感谢你的建议，在后续的版本中我会加上这两个钩子函数，如果有时间和兴趣，也可以提交pr参与进来。

2021年4月21日 上午11:51，mrzhangs520 ***@***.******@***.***>> 写道：



[image]<https://user-images.githubusercontent.com/48706034/115494033-6731a400-a297-11eb-9b1e-89bc6060d33d.png>
你好，项目作者。希望这里能增加两个个func，用来预处理rpc请求前置和后置。例如：
注册一个前置func，用来鉴定请求权限。
注册一个后置func，用来记录rpc日志。
等等。。。
